name: Run tests on Pull Request
on: [push]
jobs:
  run-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Check out repo code
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: "2.7"
      - name: Install dependencies
        run: python -m pip install -r dev-requirements.txt
      - name: Run Tests
        run: pytest tests
